version: "3.2"
services:
  schoolify_app:
    build: ./app
    image: amakundu/nodejs-mysql-app
    env_file: ./app/.env
    networks:
      - frontend
      - backend
    volumes:
      - ./app/:/dev_app
      - /dev_app/node_modules
    ports:
      - "7400:8005"
    container_name: container-schoolify-app
  schoolify_db:
    image: mysql:latest
    hostname: schoolify_db
    cap_add:
      - SYS_NICE  
    env_file: ./app/.env
    networks:
      - backend
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "7410:3306"
    container_name: container-schoolify-db
  schoolify_admin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - schoolify_db
    networks:
      - backend
    ports:
      - "7420:80"
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: schoolify_db
    volumes:
      - /sessions
    container_name: container-schoolify-admin
networks:
  frontend:
  backend: